/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniformsRouteImport } from './routes/uniforms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as SecurityUniformsRouteImport } from './routes/security-uniforms'
import { Route as NccRouteImport } from './routes/ncc'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const UniformsRoute = UniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityUniformsRoute = SecurityUniformsRouteImport.update({
  id: '/security-uniforms',
  path: '/security-uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const NccRoute = NccRouteImport.update({
  id: '/ncc',
  path: '/ncc',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/ncc': typeof NccRoute
  '/security-uniforms': typeof SecurityUniformsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/ncc': typeof NccRoute
  '/security-uniforms': typeof SecurityUniformsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessories': typeof AccessoriesRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/ncc': typeof NccRoute
  '/security-uniforms': typeof SecurityUniformsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessories'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/ncc'
    | '/security-uniforms'
    | '/shoes'
    | '/shop'
    | '/uniforms'
    | '/product/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessories'
    | '/contact'
    | '/gallery'
    | '/ncc'
    | '/security-uniforms'
    | '/shoes'
    | '/shop'
    | '/uniforms'
    | '/product/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessories'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/ncc'
    | '/security-uniforms'
    | '/shoes'
    | '/shop'
    | '/uniforms'
    | '/product/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  NccRoute: typeof NccRoute
  SecurityUniformsRoute: typeof SecurityUniformsRoute
  ShoesRoute: typeof ShoesRoute
  ShopRoute: typeof ShopRoute
  UniformsRoute: typeof UniformsRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uniforms': {
      id: '/uniforms'
      path: '/uniforms'
      fullPath: '/uniforms'
      preLoaderRoute: typeof UniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-uniforms': {
      id: '/security-uniforms'
      path: '/security-uniforms'
      fullPath: '/security-uniforms'
      preLoaderRoute: typeof SecurityUniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncc': {
      id: '/ncc'
      path: '/ncc'
      fullPath: '/ncc'
      preLoaderRoute: typeof NccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessoriesRoute: AccessoriesRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  NccRoute: NccRoute,
  SecurityUniformsRoute: SecurityUniformsRoute,
  ShoesRoute: ShoesRoute,
  ShopRoute: ShopRoute,
  UniformsRoute: UniformsRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
