/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniformsRouteImport } from './routes/uniforms'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as IndexRouteImport } from './routes/index'

const UniformsRoute = UniformsRouteImport.update({
  id: '/uniforms',
  path: '/uniforms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/uniforms': typeof UniformsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/shoes' | '/shop' | '/uniforms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/shoes' | '/shop' | '/uniforms'
  id: '__root__' | '/' | '/shoes' | '/shop' | '/uniforms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShoesRoute: typeof ShoesRoute
  ShopRoute: typeof ShopRoute
  UniformsRoute: typeof UniformsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uniforms': {
      id: '/uniforms'
      path: '/uniforms'
      fullPath: '/uniforms'
      preLoaderRoute: typeof UniformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShoesRoute: ShoesRoute,
  ShopRoute: ShopRoute,
  UniformsRoute: UniformsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
